# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    ## arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactStagingDirectory)'
    zipAfterPublish: True

 
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    ## PathtoPublish: '$(build.artifactstagingdirectory)'
    PathtoPublish: '$(build.artifactStagingDirectory)'
  condition: succeededOrFailed()

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription-CloudAppDev (a7443664-156e-4bcf-be37-df7d4e595532)'
    appType: 'webApp'
    WebAppName: 'KAD-DotNetApplicationApp'
    packageForLinux: '$(build.artifactStagingDirectory)/**/aspnetcore-webapp.zip'

